### ISSUE TITLE
Cannot compile in IDE1.6.8 because of jog.c error: unknown type name 'plan_line_data_t'

### ISSUE THREAD

**Issue by denmorru** [gnea/grbl#159]
> jog.c:25: error: unknown type name 'plan_line_data_t'
>  uint8_t jog_execute(plan_line_data_t *pl_data, parser_block_t *gc_block)
> exit status 1
> unknown type name 'plan_line_data_t'

**Comment by denmorru** [comment]
Solution: 
delete files jog.c and jog.h
they are from other version

**Comment by chamnit** [comment]
@denmorru : That is not the correct solution. Please follow the wiki instructions on compiling Grbl with the Arduino IDE. First, you need to use the GrblUpload example to compile it, and you need to remove any existing grbl installations in your Arduino library. If you don't follow these instructions exactly, you can have problems like this.
